### ISSUE TITLE
soap_tf2dm crashes server on pass time maps

### ISSUE THREAD

**Issue by Arie** [sapphonie/SOAP-TF2DM#24]
- Load a pass time map, e.g. pass_brickyard
- Spawn
- Server crashes

https://crash.limetech.org/zmj4hn4gjqrh

**Comment by sapphonie** [comment]
![image](https://user-images.githubusercontent.com/15315481/151253957-4399302a-3bb3-4cc3-9286-7ea07d12bc5f.png)

**Comment by sapphonie** [comment]
related to disabling `team_round_timer` entities fsr

**Comment by sapphonie** [comment]
#27
