### ISSUE TITLE
Arena logic not working with SoapDM/SoapTournament

### ISSUE THREAD

**Issue by H20Gamez** [sapphonie/SOAP-TF2DM#36]
SoapDM doesn't seem to work with arena mode at all. I've tried both Soap Tournament unloading the plugin before the match starts and the console command. The logic just seems to get deleted with SoapDM (i.e. announcer gone and doors wont open). I'm running an Arena tournament with 40 teams this weekend and I really have no clue what I can seriously do because I've tried almost everything I can think of.

**Comment by sapphonie** [comment]
#37
