### ISSUE TITLE
Some players stay ubercharged after spawning

### ISSUE THREAD

**Issue by atagen** [sapphonie/SOAP-TF2DM#9]
The uber effect given in Event_player_spawn with `TF2_AddCondition(client, TFCond_UberchargedHidden, TFCondDuration_Infinite, 0);` doesn't always seem to hit the code path intended to check for spawn being occupied in `RandomSpawn` to have it removed. This is not consistent for all players, leading to some being damageable while others aren't.

I've experienced this several times in recent matches, most notably on maps that don't have SOAP spawns defined for them.

**Comment by sapphonie** [comment]
Hi!

I've entirely reworked the spawning stuff in the latest version, which is about ready for a push. Could you please check if this is still an issue with [the plugin on the alpha branch](https://github.com/sapphonie/SOAP-TF2DM/blob/alpha/addons/sourcemod/plugins/soap_tf2dm.smx)?

Thanks!

**Comment by atagen** [comment]
hi,

appears that this alpha version doesn't activate on maps without a spawn; it throws the expected "no spawns found" error in console but no health regen, near-instant respawn, etc.
works fine on maps where it would be expected to, but now seems to be missing some features (such as displaying your attacker's health status on death).

imo incorporating `SetDefaultSpawns()` function as a final fallthrough for situations where no other spawn points can be established keeps server behaviour consistent with the admin's intention - with authors not updating soapdm spawns for new releases and with new maps being tested for competitive use, it's nice to still have a ~functional dm between rounds.

I'm happy to integrate said functionality into this alpha branch. just let me know.

as an aside, I had an idea to maybe also distribute some random spawns in a radius around capture points, to prevent trekking and preserve dm feel? would be interested to hear your thoughts on this.
btw, kudos on fixing the duplicated load routine for the `g_h*Spawns` arrays , it did strike me as odd when I was first reviewing :)

thanks

**Comment by sapphonie** [comment]
yep, if you could rebase it on alpha id be more than happy to take a look as it would ALSO help me with implementing #8

**Comment by atagen** [comment]
rebase completed, seems fine in testing. hope this helps 👍
